version: "3.9"
services:
  analysisDb:
    image: postgres:11
    restart: "always"
    ports: 
      - "5432:5432"
    volumes:
      - ./sql/analysisDb_create_tables.sql:/docker-entrypoint-initdb.d/analysisDb_create_tables.sql
      - ./sql/analysisDb_fill_tables.sql:/docker-entrypoint-initdb.d/analysisDb_fill_tables.sql
    environment:
      POSTGRES_DB: "analysisDb"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "123456"