version: "3.9"
services:
  analysisDb:
    image: postgres:11
    restart: "always"
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_DB: "analysisDb"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "123456"
  queue:
    image: rabbitmq:3.10-management
    ports: 
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin" 
      RABBITMQ_DEFAULT_PASS: "123456"