CREATE TABLE "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE "Results" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Operation" text NOT NULL,
    "Message" text NOT NULL,
    "IsSuccess" boolean NOT NULL,
    "Value" text NOT NULL,
    CONSTRAINT "PK_Results" PRIMARY KEY ("Id")
);